import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const VOXTRAL_API_URL = Deno.env.get('VOXTRAL_API_URL') || 'https://api.voxtral.com/v1'
const VOXTRAL_API_KEY = Deno.env.get('VOXTRAL_API_KEY')

serve(async (req) => {
  try {
    const { meetingId, audioUrl, organizationId } = await req.json()

    if (!meetingId || !audioUrl || !organizationId) {
      return new Response(
        JSON.stringify({ error: 'Missing required parameters' }),
        { status: 400, headers: { 'Content-Type': 'application/json' } }
      )
    }

    // Initialize Supabase client
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    const supabase = createClient(supabaseUrl, supabaseServiceKey)

    // Download audio file from Supabase Storage
    const audioResponse = await fetch(audioUrl)
    if (!audioResponse.ok) {
      throw new Error('Failed to download audio file')
    }

    const audioBlob = await audioResponse.blob()

    // Call Voxtral API for transcription
    if (!VOXTRAL_API_KEY) {
      // Mock transcription for development
      const mockTranscript = `Meeting transcript for ${meetingId}. This is a placeholder transcription. In production, this would be generated by Voxtral Mini 3B running on ISAIC infrastructure.`
      
      // Store transcript
      const { data: transcript, error: transcriptError } = await supabase
        .from('transcripts')
        .insert({
          meeting_id: meetingId,
          organization_id: organizationId,
          raw_text: mockTranscript,
          structured_data: {},
          voxtral_metadata: { mock: true },
        })
        .select()
        .single()

      if (transcriptError) {
        throw transcriptError
      }

      // Update meeting status
      await supabase
        .from('meetings')
        .update({ status: 'transcribed' })
        .eq('id', meetingId)

      // Trigger MeetingMind agent for action extraction
      const { error: agentError } = await supabase.functions.invoke('meetingmind-agent', {
        body: {
          meetingId,
          transcriptId: transcript.id,
          organizationId,
        },
      })

      if (agentError) {
        console.error('Agent invocation error:', agentError)
      }

      return new Response(
        JSON.stringify({
          success: true,
          transcriptId: transcript.id,
          message: 'Mock transcription completed',
        }),
        { headers: { 'Content-Type': 'application/json' } }
      )
    }

    // Real Voxtral transcription
    const formData = new FormData()
    formData.append('audio', audioBlob, 'audio.mp3')
    formData.append('language', 'en')
    formData.append('model', 'voxtral-mini-3b')

    const voxtralResponse = await fetch(`${VOXTRAL_API_URL}/transcribe`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${VOXTRAL_API_KEY}`,
      },
      body: formData,
    })

    if (!voxtralResponse.ok) {
      throw new Error(`Voxtral API error: ${voxtralResponse.statusText}`)
    }

    const voxtralData = await voxtralResponse.json()
    const transcriptText = voxtralData.text || voxtralData.transcript

    // Store transcript
    const { data: transcript, error: transcriptError } = await supabase
      .from('transcripts')
      .insert({
        meeting_id: meetingId,
        organization_id: organizationId,
        raw_text: transcriptText,
        structured_data: voxtralData.structured || {},
        voxtral_metadata: voxtralData.metadata || {},
      })
      .select()
      .single()

    if (transcriptError) {
      throw transcriptError
    }

    // Update meeting status
    await supabase
      .from('meetings')
      .update({ status: 'transcribed' })
      .eq('id', meetingId)

    // Trigger MeetingMind agent for action extraction
    const { error: agentError } = await supabase.functions.invoke('meetingmind-agent', {
      body: {
        meetingId,
        transcriptId: transcript.id,
        organizationId,
      },
    })

    if (agentError) {
      console.error('Agent invocation error:', agentError)
    }

    return new Response(
      JSON.stringify({
        success: true,
        transcriptId: transcript.id,
      }),
      { headers: { 'Content-Type': 'application/json' } }
    )
  } catch (error) {
    console.error('Transcription error:', error)
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { 'Content-Type': 'application/json' } }
    )
  }
})
